export const markdownInitialCode = `[h1]SomMark: Markdown Showcase[end]

[Block]
This example demonstrates SomMark's support for standard Markdown features when using the \\\`--markdown\\\` format.
[end]

[h2]Formatting[end]

[Block]
You can use [bold]bold text[end], [italic]italic text[end], and [emphasis]emphasis[end] easily.
[end]
[h2]Lists[end]

[Block]
@_list_@;
- Item 1
- Item 2
    - Sub-item A
    - Sub-item B
- Item 3
@_end_@
[end]

[h1]Daily Project Tasks[end]

[h2]Project: SomMark v3.0[end]

[todo = Implement dynamic HTML tag registration]done[end]
[todo = Add full Markdown support]done[end]
[todo = Refactor identifier validation]done[end]
[todo = Implement block newline enforcement]- [end]
[todo = Release Beta version]x[end]


[h2]Notes[end]

[Block]
Remember to [italic]verify all tests[end] before pushing any changes to the main branch.
[end]

[h2]Code blocks[end]

[Block]
@_Code_@: javascript;
function hello() {
  console.log("Hello from SomMark!");
}
@_end_@
[end]

[h2]Tables[end]

[Block]
@_Table_@: Feature, Status, Priority;
Markdown Support, Done, High
HTML Support, Done, High
JSON Support, Done, Medium
@_end_@
[end]

[h1]Developer Documentation: Core Module[end]

[Block]
This document provides an overview of the core module architecture.
[end]

[h2]Architecture Overview[end]

[Block]
The system is divided into three primary stages:
1. **Lexer**: Tokenizes the raw input.
2. **Parser**: Builds an Abstract Syntax Tree \(AST\).
3. **Transpiler**: Generates the final output based on the target format.
[end]

[h2]API Reference[end]

[h3]Function: transpile[end]

[Block]
@_Table_@: Parameter, Type, Description;
ast, array, The Abstract Syntax Tree generated by the parser.
format, string, The target output format (html\, markdown\, json).
mapperFile, object, Custom mapping definitions.
@_end_@
[end]

[h3]Usage[end]

[Block]
@_Code_@: javascript;
import { transpile } from './core/transpiler.js';

const result = await transpile({
  ast: myAst,
  format: 'html'
});
@_end_@
[end] `;

